# Generated by Django 2.2.28 on 2022-11-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addresswtcmdhnecf'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresswtcmdhnecf',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
